# Pandas 기본

## DataFrame 컬럼을 Python 배열이나 Numpy 배열로 변환하기

In [1]:
import pandas as pd

data_dict = {
    'one': pd.Series([1, 2, 3], index=['a', 'b', 'c'])
    , 'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    , 'three': pd.Series([5, 6, 7, 8], index=['a', 'b', 'c', 'd'])
}

df = pd.DataFrame(data_dict)

print(f'DataFrame:\n{df}\n')
print(f'column types:\n{df.dtypes}\n')

DataFrame:
   one  two  three
a  1.0    1      5
b  2.0    2      6
c  3.0    3      7
d  NaN    4      8

column types:
one      float64
two        int64
three      int64
dtype: object



In [2]:
col_one_list = df['one'].tolist()
col_one_arr = df['one'].to_numpy()

print(f'\ncol_one_list:\n{col_one_list}\ntype:{type(col_one_list)}')
print(f'\ncol_one_arr:\n{col_one_arr}\ntype:{type(col_one_arr)}')


col_one_list:
[1.0, 2.0, 3.0, nan]
type:<class 'list'>

col_one_arr:
[ 1.  2.  3. nan]
type:<class 'numpy.ndarray'>


In [3]:
np_arr1 = df.to_numpy()
print(np_arr1)

[[ 1.  1.  5.]
 [ 2.  2.  6.]
 [ 3.  3.  7.]
 [nan  4.  8.]]


In [4]:
np_arr2 = df[['one', 'two']].to_numpy()
print(np_arr2)

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [nan  4.]]


처음 세 행과 첫 번째, 세 번째 열을 출력합니다.

In [5]:
np_arr3 = df.iloc[[0, 1, 2], [0, 2]].to_numpy()
print(np_arr3)

[[1. 5.]
 [2. 6.]
 [3. 7.]]
