# Pandas 기본 실습

Pandas 기본 문법을 실습하기 위한 노트북입니다.

## DataFrame 컬럼을 Python 배열이나 Numpy 배열로 변환하기

In [1]:
import pandas as pd

data_dict = {
    'one': pd.Series([1, 2, 3], index=['a', 'b', 'c'])
    , 'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    , 'three': pd.Series([5, 6, 7, 8], index=['a', 'b', 'c', 'd'])
}

df = pd.DataFrame(data_dict)

print(f'DataFrame:\n{df}\n')
print(f'column types:\n{df.dtypes}\n')

DataFrame:
   one  two  three
a  1.0    1      5
b  2.0    2      6
c  3.0    3      7
d  NaN    4      8

column types:
one      float64
two        int64
three      int64
dtype: object



In [2]:
col_one_list = df['one'].tolist()
col_one_arr = df['one'].to_numpy()

print(f'\ncol_one_list:\n{col_one_list}\ntype:{type(col_one_list)}')
print(f'\ncol_one_arr:\n{col_one_arr}\ntype:{type(col_one_arr)}')


col_one_list:
[1.0, 2.0, 3.0, nan]
type:<class 'list'>

col_one_arr:
[ 1.  2.  3. nan]
type:<class 'numpy.ndarray'>


In [3]:
np_arr1 = df.to_numpy()
print(np_arr1)

[[ 1.  1.  5.]
 [ 2.  2.  6.]
 [ 3.  3.  7.]
 [nan  4.  8.]]


In [4]:
np_arr2 = df[['one', 'two']].to_numpy()
print(np_arr2)

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [nan  4.]]


처음 세 행과 첫 번째, 세 번째 열을 출력합니다.

In [5]:
np_arr3 = df.iloc[[0, 1, 2], [0, 2]].to_numpy()
print(np_arr3)

[[1. 5.]
 [2. 6.]
 [3. 7.]]


## DataFrame 컬럼에 대해 그룹별 합 구하기

In [6]:
df = pd.DataFrame.from_dict({
    'Name': ['Bob', 'Bob', 'Mike', 'Mike', 'Mike', 'Tom']
    , 'Fruit': ['Apple', 'Orange', 'Grape', 'Apple', 'Apple', 'Orange']
    , 'Count': [1, 2, 3, 4, 5, 6]    
})

print(df)

   Name   Fruit  Count
0   Bob   Apple      1
1   Bob  Orange      2
2  Mike   Grape      3
3  Mike   Apple      4
4  Mike   Apple      5
5   Tom  Orange      6


In [7]:
df[['Name', 'Count']].groupby('Name').sum()

Count
Name       
Bob       3
Mike     12
Tom       6

In [8]:
df[['Name', 'Fruit', 'Count']].groupby(['Name', 'Fruit']).sum()

Count
Name Fruit        
Bob  Apple       1
     Orange      2
Mike Apple       9
     Grape       3
Tom  Orange      6

In [9]:
grouped_df = df[['Name', 'Fruit', 'Count']].groupby(['Name', 'Fruit'], as_index=False)
print(grouped_df.sum())
print(grouped_df)

   Name   Fruit  Count
0   Bob   Apple      1
1   Bob  Orange      2
2  Mike   Apple      9
3  Mike   Grape      3
4   Tom  Orange      6


In [10]:
grouped_df.groups.keys()

dict_keys([('Bob', 'Apple'), ('Bob', 'Orange'), ('Mike', 'Apple'), ('Mike', 'Grape'), ('Tom', 'Orange')])

In [11]:
df[['Name', 'Fruit', 'Count']].groupby(['Name', 'Fruit'], as_index=False).count()

Name   Fruit  Count
0   Bob   Apple      1
1   Bob  Orange      1
2  Mike   Apple      2
3  Mike   Grape      1
4   Tom  Orange      1

In [12]:
df[['Name', 'Fruit', 'Count']].groupby(['Name', 'Fruit']).size().reset_index(name='size')['size']

0    1
1    1
2    2
3    1
4    1
Name: size, dtype: int64

## DataFrame 컬럼에 대해 누적 합 구하기

참고 자료

* [4 Ways to Calculate Pandas Cumulative Sum](https://datagy.io/pandas-cumulative-sum/), Nik Piepenbreier

In [13]:
df = pd.DataFrame.from_dict({
    'Type': ['A', 'B', 'A', 'A', 'A', 'B', 'A', 'B', 'B']
    , 'Date': ['01-Jan-21', '01-Jan-21', '02-Jan-21', '03-Jan-21', '05-Jan-21', '07-Jan-21', '09-Jan-21', '10-Jan-21', '11-Jan-21']
    , 'Sales': [10, 15, 7, 23, 18, 7, 3, 10, 25]
    , 'Profits': [3, 5, 2, 7, 6, 2, 1, 3, 8]
})

print(df)

  Type       Date  Sales  Profits
0    A  01-Jan-21     10        3
1    B  01-Jan-21     15        5
2    A  02-Jan-21      7        2
3    A  03-Jan-21     23        7
4    A  05-Jan-21     18        6
5    B  07-Jan-21      7        2
6    A  09-Jan-21      3        1
7    B  10-Jan-21     10        3
8    B  11-Jan-21     25        8


`Sales` 열의 누적 합을 구하고 새로운 열 `Cumulative Sales`에 저장합니다.

In [14]:
df['Cumulative Sales'] = df['Sales'].cumsum()

print(df)

  Type       Date  Sales  Profits  Cumulative Sales
0    A  01-Jan-21     10        3                10
1    B  01-Jan-21     15        5                25
2    A  02-Jan-21      7        2                32
3    A  03-Jan-21     23        7                55
4    A  05-Jan-21     18        6                73
5    B  07-Jan-21      7        2                80
6    A  09-Jan-21      3        1                83
7    B  10-Jan-21     10        3                93
8    B  11-Jan-21     25        8               118


### `Null` 값이 있는 경우에 누적 합 구하기

In [15]:
import numpy as np

df.loc[5, 'Sales'] = np.NaN

print(df)

  Type       Date  Sales  Profits  Cumulative Sales
0    A  01-Jan-21   10.0        3                10
1    B  01-Jan-21   15.0        5                25
2    A  02-Jan-21    7.0        2                32
3    A  03-Jan-21   23.0        7                55
4    A  05-Jan-21   18.0        6                73
5    B  07-Jan-21    NaN        2                80
6    A  09-Jan-21    3.0        1                83
7    B  10-Jan-21   10.0        3                93
8    B  11-Jan-21   25.0        8               118


In [16]:
df['Cumulative Sales'] = df['Sales'].cumsum()

print(df)

  Type       Date  Sales  Profits  Cumulative Sales
0    A  01-Jan-21   10.0        3              10.0
1    B  01-Jan-21   15.0        5              25.0
2    A  02-Jan-21    7.0        2              32.0
3    A  03-Jan-21   23.0        7              55.0
4    A  05-Jan-21   18.0        6              73.0
5    B  07-Jan-21    NaN        2               NaN
6    A  09-Jan-21    3.0        1              76.0
7    B  10-Jan-21   10.0        3              86.0
8    B  11-Jan-21   25.0        8             111.0


`cumsum()` 메쏘드의 `skipna` 파라미터의 값을 `False`로 설정하면 `NaN` 부터는 모든 값을 무시합니다.

In [17]:
df['Cumulative Sales'] = df['Sales'].cumsum(skipna=False)

print(df)

  Type       Date  Sales  Profits  Cumulative Sales
0    A  01-Jan-21   10.0        3              10.0
1    B  01-Jan-21   15.0        5              25.0
2    A  02-Jan-21    7.0        2              32.0
3    A  03-Jan-21   23.0        7              55.0
4    A  05-Jan-21   18.0        6              73.0
5    B  07-Jan-21    NaN        2               NaN
6    A  09-Jan-21    3.0        1               NaN
7    B  10-Jan-21   10.0        3               NaN
8    B  11-Jan-21   25.0        8               NaN


### 그룹별로 누적 합 구하기 

In [18]:
# NaN으로 지정했던 값을 원래의 값으로 돌려 놓습니다.
df.loc[5, 'Sales'] = 7

df['Grouped Cumulative Sum'] = df[['Type', 'Sales']].groupby('Type').cumsum()

print(df)

  Type       Date  Sales  Profits  Cumulative Sales  Grouped Cumulative Sum
0    A  01-Jan-21   10.0        3              10.0                    10.0
1    B  01-Jan-21   15.0        5              25.0                    15.0
2    A  02-Jan-21    7.0        2              32.0                    17.0
3    A  03-Jan-21   23.0        7              55.0                    40.0
4    A  05-Jan-21   18.0        6              73.0                    58.0
5    B  07-Jan-21    7.0        2               NaN                    22.0
6    A  09-Jan-21    3.0        1               NaN                    61.0
7    B  10-Jan-21   10.0        3               NaN                    32.0
8    B  11-Jan-21   25.0        8               NaN                    57.0


### 누적 백분율 구하기

In [19]:
df['Cumulative Sales Percentage'] = df['Sales'].cumsum() / df['Sales'].sum()

print(df)

  Type       Date  Sales  Profits  Cumulative Sales  Grouped Cumulative Sum  \
0    A  01-Jan-21   10.0        3              10.0                    10.0   
1    B  01-Jan-21   15.0        5              25.0                    15.0   
2    A  02-Jan-21    7.0        2              32.0                    17.0   
3    A  03-Jan-21   23.0        7              55.0                    40.0   
4    A  05-Jan-21   18.0        6              73.0                    58.0   
5    B  07-Jan-21    7.0        2               NaN                    22.0   
6    A  09-Jan-21    3.0        1               NaN                    61.0   
7    B  10-Jan-21   10.0        3               NaN                    32.0   
8    B  11-Jan-21   25.0        8               NaN                    57.0   

   Cumulative Sales Percentage  
0                     0.084746  
1                     0.211864  
2                     0.271186  
3                     0.466102  
4                     0.618644  
5          

DataFrame의 `apply()` 메쏘드를 통해 백분율 출력 형식을 지정할 수 있습니다.

In [20]:
df['Cumulative Sales Percentage'] = df['Cumulative Sales Percentage'].apply(lambda x: f'{x:.2%}')

print(df)

  Type       Date  Sales  Profits  Cumulative Sales  Grouped Cumulative Sum  \
0    A  01-Jan-21   10.0        3              10.0                    10.0   
1    B  01-Jan-21   15.0        5              25.0                    15.0   
2    A  02-Jan-21    7.0        2              32.0                    17.0   
3    A  03-Jan-21   23.0        7              55.0                    40.0   
4    A  05-Jan-21   18.0        6              73.0                    58.0   
5    B  07-Jan-21    7.0        2               NaN                    22.0   
6    A  09-Jan-21    3.0        1               NaN                    61.0   
7    B  10-Jan-21   10.0        3               NaN                    32.0   
8    B  11-Jan-21   25.0        8               NaN                    57.0   

  Cumulative Sales Percentage  
0                       8.47%  
1                      21.19%  
2                      27.12%  
3                      46.61%  
4                      61.86%  
5                

## 기존의 DataFrame에 행 추가하기

In [21]:
dict = {
    'Name':['Martha', 'Tim', 'Rob', 'Georgia']
    , 'Maths':[87, 91, 97, 95]
    , 'Science':[83, 99, 84, 76] 
} 
  
df = pd.DataFrame(dict) 
  
df.loc[len(df.index)] = ['Amy', 89, 93]  
  
print(df) 

      Name  Maths  Science
0   Martha     87       83
1      Tim     91       99
2      Rob     97       84
3  Georgia     95       76
4      Amy     89       93


## 컬럼 이름을 지정하여 비어 있는 DataFrame 만들기

In [22]:
# Create an empty DataFrame with column names
df = pd.DataFrame(columns=['Column 1', 'Column 2', 'Column 3'])
print(df)

Empty DataFrame
Columns: [Column 1, Column 2, Column 3]
Index: []


컬럼별로 데이터 유형을 지정하여 DataFrame을 생성할 수 있습니다.

In [23]:
# Create an empty DataFrame with column names and data types
schema={'Column 1': 'int64', 'Column 2': 'float64'}
df = pd.DataFrame(columns=schema.keys()).astype(schema)
print(df.dtypes)

Column 1      int64
Column 2    float64
dtype: object


## 조건에 따라 컬럼 값 바꾸기

In [27]:
Students = {
    'name': ['John', 'Jay', 'Sachin', 'Geetha', 'Amutha', 'Ganesh']
    , 'gender': ['male', 'male', 'male', 'female', 'female', 'male']
    , 'math score': [50, 100, 70, 80, 75, 40]
}

df = pd.DataFrame(Students)
df

name  gender  math score
0    John    male          50
1     Jay    male         100
2  Sachin    male          70
3  Geetha  female          80
4  Amutha  female          75
5  Ganesh    male          40

### DataFrame.loc[] 사용

In [28]:
df['gender'] == 'male'

0     True
1     True
2     True
3    False
4    False
5     True
Name: gender, dtype: bool

In [26]:
df.loc[df['gender'] == 'male', 'gender']

0    male
1    male
2    male
5    male
Name: gender, dtype: object

In [29]:
df.loc[df['gender'] == 'male', 'gender'] = 1
df

name  gender  math score
0    John       1          50
1     Jay       1         100
2  Sachin       1          70
3  Geetha  female          80
4  Amutha  female          75
5  Ganesh       1          40

### Numpy.where() 사용

In [30]:
df2 = pd.DataFrame(Students)

df2['gender'] = np.where(df2['gender'] == 'female', 0, 1)
df2

name  gender  math score
0    John       1          50
1     Jay       1         100
2  Sachin       1          70
3  Geetha       0          80
4  Amutha       0          75
5  Ganesh       1          40

### DataFrame.mask() 사용

In [33]:
df3 = pd.DataFrame(Students)

df3['gender'].mask(df['gender'] == 'female', 0, inplace=True)
df3

name gender  math score
0    John   male          50
1     Jay   male         100
2  Sachin   male          70
3  Geetha      0          80
4  Amutha      0          75
5  Ganesh   male          40

### DataFrame.apply() 사용

In [36]:
df4 = pd.DataFrame(Students)

df4['gender'] = df['gender'].apply(lambda x: 0 if x == 'female' else x)
df4

name  gender  math score
0    John       1          50
1     Jay       1         100
2  Sachin       1          70
3  Geetha       0          80
4  Amutha       0          75
5  Ganesh       1          40